[preset]
rules = [
  { when_file = "docker-compose.yml" },
  { when_file = "composer.json" }
]

[tasks.composer]
description = "Run composer inside the container"
command = "docker compose -p ${PROJECT:-$CWD} exec -e COLUMNS=$(tput cols) -e LINES=$(tput lines) -it app composer"
