name: Bump

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
    - uses: actions/checkout@v2

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        tag_prefix: ''
        github_token: ${{ secrets.TOKEN }}
